#!/usr/bin/env tsx
/**
 * @fileoverview sync-changelog.ts
 *
 * Generates the root CHANGELOG.md from v3/src/lib/changelog.ts — the developers' per-push
 * record, grouped by commit type in the Keep a Changelog layout (ADR-0063). The app shows its
 * own release notes, v3/src/lib/whatsNew.ts. The hand-kept CHANGELOG.md had stopped at
 * 0.3.0 / "Slice 4 in progress" in May 2026 while the app reached 3.0.5x (ADR-0050).
 *
 * Run: npm run sync:changelog  (from v3/) — part of npm run sync:docs.
 */

import { dirname, join, resolve } from 'path';
import { fileURLToPath } from 'url';
import { APP_VERSION, CHANGELOG } from '../src/lib/changelog';
import { writeGenerated } from './lib/write-generated';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TARGET = join(resolve(__dirname, '..', '..'), 'CHANGELOG.md');

if (CHANGELOG[0]?.version !== APP_VERSION) {
  console.error(
    `❌ sync-changelog: newest entry ${CHANGELOG[0]?.version} ≠ APP_VERSION ${APP_VERSION}`,
  );
  process.exit(1);
}

/**
 * Keep a Changelog groups (ADR-0063), in this order. Each commit type maps to one group;
 * "Internal" is our deviation — docs, tests and tooling stay visible to developers here and are
 * never shown in the app.
 */
const GROUPS: [heading: string, types: string[]][] = [
  ['Added', ['feat']],
  ['Changed', ['perf', 'refactor', 'a11y', 'security', 'revert']],
  ['Fixed', ['fix']],
  ['Internal', ['docs', 'test', 'ci', 'build', 'chore', 'style']],
];

/** The commit type an item starts with, e.g. "fix" for "fix(pads): …". */
function typeOf(item: string): string {
  const type = /^([a-z0-9]+)(\([^)]+\))?!?: /.exec(item)?.[1];
  if (!type) throw new Error(`sync-changelog: item without a commit type: ${item.slice(0, 60)}`);
  return type;
}

const lines = [
  '# Changelog',
  '',
  '<!-- AUTO-GENERATED by `npm run sync:changelog` from v3/src/lib/changelog.ts — do not edit. -->',
  '',
  'All notable changes to Soundboard of Storytelling, for developers, newest first. The layout',
  'follows [Keep a Changelog](https://keepachangelog.com/en/1.1.0/); "Internal" is our own group for',
  'documentation, tests and tooling. Versions count pushes (3.0.N), not Semantic Versioning. The',
  'release notes the app shows are written separately for its users (`v3/src/lib/whatsNew.ts`).',
  '',
];
for (const entry of CHANGELOG) {
  lines.push(`## ${entry.version} — ${entry.date}`, '');
  for (const [heading, types] of GROUPS) {
    const items = entry.items.filter((i) => types.includes(typeOf(i)));
    if (items.length === 0) continue;
    lines.push(`### ${heading}`, '');
    for (const item of items) lines.push(`- ${item}`);
    lines.push('');
  }
  const known = GROUPS.flatMap(([, types]) => types);
  const unknown = entry.items.filter((i) => !known.includes(typeOf(i)));
  if (unknown.length) throw new Error(`sync-changelog: no group for ${unknown.join(' / ')}`);
}
const next = lines.join('\n');

if (await writeGenerated(TARGET, next)) {
  console.log(`✅ CHANGELOG.md regenerated (${CHANGELOG.length} releases).`);
} else {
  console.log('✅ CHANGELOG.md already up to date.');
}
