#!/usr/bin/env tsx
/**
 * sync-changelog.ts
 *
 * Generates the root CHANGELOG.md from v3/src/lib/changelog.ts — the single source of
 * release notes (also shown in the app). The hand-kept CHANGELOG.md had stopped at
 * 0.3.0 / "Slice 4 in progress" in May 2026 while the app reached 3.0.5x (ADR-0050).
 *
 * Run: npm run sync:changelog  (from v3/) — part of npm run sync:docs.
 */

import { dirname, join, resolve } from 'path';
import { fileURLToPath } from 'url';
import { APP_VERSION, CHANGELOG } from '../src/lib/changelog';
import { writeGenerated } from './lib/write-generated';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TARGET = join(resolve(__dirname, '..', '..'), 'CHANGELOG.md');

if (CHANGELOG[0]?.version !== APP_VERSION) {
  console.error(
    `❌ sync-changelog: newest entry ${CHANGELOG[0]?.version} ≠ APP_VERSION ${APP_VERSION}`,
  );
  process.exit(1);
}

const lines = [
  '# Changelog',
  '',
  '<!-- AUTO-GENERATED by `npm run sync:changelog` from v3/src/lib/changelog.ts — do not edit. -->',
  '',
  'All notable changes to Soundboard of Storytelling, newest first.',
  '',
];
for (const entry of CHANGELOG) {
  lines.push(`## ${entry.version} — ${entry.date}`, '');
  for (const item of entry.items) lines.push(`- ${item}`);
  lines.push('');
}
const next = lines.join('\n');

if (await writeGenerated(TARGET, next)) {
  console.log(`✅ CHANGELOG.md regenerated (${CHANGELOG.length} releases).`);
} else {
  console.log('✅ CHANGELOG.md already up to date.');
}
