/**
 * @fileoverview iconGuards — the pad icon collection keeps its scheme (ADR-0070)
 *
 * The files in src/icons are generated by scripts/build-icons.ts from the curated selection;
 * these checks keep what ships correct whatever the generator or a hand edit did:
 * 1. Each pack is IconifyJSON with its prefix as file name and full license facts; a license
 *    that requires its text to ship (MIT) has `<prefix>.LICENSE.txt` next to it.
 * 2. Names are kebab-case and unique per pack; `info.total` counts them.
 * 3. A drawing is one path of pixel rectangles inside the pack's grid, filled with currentColor.
 * 4. Every icon has exactly one category from the fixed list.
 * 5. The catalog has exactly the icons of the packs, each with 1–8 lower-case search words.
 * 6. No drawing appears twice in the whole collection (owner: no icon implemented twice).
 * 7. No brand logos (owner decision 2026-10-04) — names never carry a brand name.
 */
import { describe, it, expect } from 'vitest';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  ICON_CATEGORIES,
  ICON_SET_PREFIXES,
  type IconCatalog,
  type IconSetJson,
} from '../../src/lib/iconSet';

const DIR = join(__dirname, '../../src/icons');
const KEBAB = /^[a-z0-9]+(-[a-z0-9]+)*$/;
const LICENSES_WITH_TEXT = new Set(['MIT']);
const LICENSES = new Set(['CC0-1.0', ...LICENSES_WITH_TEXT]);
// Brand names that are no ordinary word (so not steam, windows, safari, chrome, apple)
const BRANDS =
  /(^|-)(adobe|amazon|android|bluesky|discord|facebook|figma|firefox|github|gitlab|gmail|google|instagram|itchio|linkedin|mastodon|microsoft|nintendo|patreon|paypal|photoshop|playstation|reddit|spotify|telegram|tiktok|twitch|twitter|whatsapp|xbox|youtube)(-|$)/;

const setFiles = readdirSync(join(DIR, 'sets')).filter((f) => f.endsWith('.json'));
const sets: IconSetJson[] = setFiles.map(
  (f) => JSON.parse(readFileSync(join(DIR, 'sets', f), 'utf8')) as IconSetJson,
);
const catalog = JSON.parse(readFileSync(join(DIR, 'catalog.json'), 'utf8')) as IconCatalog;
const keysOf = (s: IconSetJson) => Object.keys(s.icons).map((n) => `${s.prefix}:${n}`);

describe('icon packs', () => {
  it('each pack file is named after its prefix, and the loader knows exactly these packs', () => {
    expect(sets.map((s) => `${s.prefix}.json`)).toEqual(setFiles);
    expect([...ICON_SET_PREFIXES].sort()).toEqual(sets.map((s) => s.prefix).sort());
  });

  // Each check collects its problems per pack, so a failure names the pack and what is wrong
  it('each pack records its name, version, author and license; MIT ships its text', () => {
    const problems = sets.flatMap(({ prefix, info }) => {
      const textShips = existsSync(join(DIR, 'sets', `${prefix}.LICENSE.txt`));
      return [
        !KEBAB.test(prefix) && `${prefix}: prefix not kebab-case`,
        !(info.name && info.version && info.author.name) &&
          `${prefix}: name, version or author missing`,
        !/^https:\/\//.test(info.author.url) && `${prefix}: author url`,
        !LICENSES.has(info.license.spdx) && `${prefix}: license ${info.license.spdx} not allowed`,
        !/^https:\/\//.test(info.license.url) && `${prefix}: license url`,
        textShips !== LICENSES_WITH_TEXT.has(info.license.spdx) &&
          `${prefix}: ${prefix}.LICENSE.txt ${textShips ? 'not needed' : 'missing'}`,
      ].filter((p): p is string => typeof p === 'string');
    });
    expect(problems).toEqual([]);
  });

  it('names are kebab-case and info.total counts them', () => {
    const problems = sets.flatMap((s) => {
      const names = Object.keys(s.icons);
      return [
        ...names.filter((n) => !KEBAB.test(n)).map((n) => `${s.prefix}:${n} not kebab-case`),
        ...(s.info.total === names.length ? [] : [`${s.prefix}: info.total ${s.info.total}`]),
      ];
    });
    expect(problems).toEqual([]);
  });

  it('a drawing is one path of pixel rectangles inside the grid, filled with currentColor', () => {
    const PATH = /^<path fill="currentColor" d="((?:M\d+ \d+h\d+v1H\d+z)+)"\/>$/;
    const bad = sets.flatMap((s) =>
      Object.entries(s.icons)
        .filter(([, { body }]) => {
          const d = PATH.exec(body)?.[1];
          if (!d) return true;
          return [...d.matchAll(/M(\d+) (\d+)h(\d+)/g)].some(
            ([, x, y, w]) => +x + +w > s.width || +y >= s.height,
          );
        })
        .map(([n]) => `${s.prefix}:${n}`),
    );
    expect(bad).toEqual([]);
  });

  it('every icon has exactly one category from the fixed list', () => {
    const known: readonly string[] = ICON_CATEGORIES;
    const problems = sets.flatMap((s) => {
      const listed = Object.values(s.categories).flat();
      const unlisted = Object.keys(s.icons).filter((n) => !listed.includes(n));
      return [
        ...Object.keys(s.categories)
          .filter((c) => !known.includes(c))
          .map((c) => `${s.prefix}: unknown category ${c}`),
        ...listed
          .filter((n, i) => listed.indexOf(n) !== i)
          .map((n) => `${s.prefix}:${n} in two categories`),
        ...unlisted.map((n) => `${s.prefix}:${n} in no category`),
        ...listed.filter((n) => !s.icons[n]).map((n) => `${s.prefix}:${n} listed, no icon`),
      ];
    });
    expect(problems).toEqual([]);
  });
});

describe('catalog and collection', () => {
  it('the catalog has exactly the icons of the packs', () => {
    expect(Object.keys(catalog).sort()).toEqual(sets.flatMap(keysOf).sort());
  });

  it('each icon has 1–8 lower-case search words and its original reference', () => {
    const bad = Object.entries(catalog).filter(
      ([, { tags, source }]) =>
        tags.length < 1 ||
        tags.length > 8 ||
        tags.some((t) => !/^[a-z0-9][a-z0-9 -]*$/.test(t)) ||
        !source,
    );
    expect(bad.map(([k]) => k)).toEqual([]);
  });

  it('no drawing appears twice in the whole collection', () => {
    const seen = new Map<string, string>();
    const twice: string[] = [];
    for (const s of sets) {
      for (const [name, { body }] of Object.entries(s.icons)) {
        const id = `${s.width}:${body}`;
        const first = seen.get(id);
        if (first) twice.push(`${first} = ${s.prefix}:${name}`);
        else seen.set(id, `${s.prefix}:${name}`);
      }
    }
    expect(twice).toEqual([]);
  });

  it('no icon is named after a brand (brand logos are left out)', () => {
    expect(sets.flatMap(keysOf).filter((k) => BRANDS.test(k.split(':')[1]))).toEqual([]);
  });
});
