/**
 * @fileoverview Vite configuration — build, PWA and the license notice of every dependency
 *
 * The service worker is generated by vite-plugin-pwa (no hand-written one); every build ships
 * dist/third-party-licenses.txt; nothing is loaded from a third-party origin at runtime
 * (ADR-0057, checked by tests/e2e/pwa.spec.ts).
 */

import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { defineConfig, type Plugin } from 'vite';
import preact from '@preact/preset-vite';
import { VitePWA } from 'vite-plugin-pwa';

/**
 * Returns the root folder of the package a bundled module comes from — the folder after the last
 * `node_modules/` in its id (scoped names keep their scope) — or null for the app's own code and
 * virtual modules. Nested package.json files (e.g. preact/hooks) do not count as packages.
 */
function packageRootOf(id: string): string | null {
  const path = id.replace(/^\0/, '').split('?')[0];
  const marker = '/node_modules/';
  const at = path.lastIndexOf(marker);
  if (at < 0) return null;
  const [first, second] = path.slice(at + marker.length).split('/');
  return path.slice(0, at + marker.length) + (first.startsWith('@') ? `${first}/${second}` : first);
}

/**
 * Ships the license text of every package whose code is in the bundle as
 * dist/third-party-licenses.txt. The packages are read from the modules Rollup bundled, as
 * rollup-plugin-license does — so a package reached through a virtual module (workbox-window via
 * virtual:pwa-register/preact) is covered and an unused dependency is not — plus their runtime
 * dependencies, transitively: a package may ship a prebuilt file with its dependencies inside
 * (workbox-window carries workbox-core), which no module id shows; listing one too many costs
 * nothing, one too few breaks a license. MIT/ISC require the notice in copies; the self-hosted
 * fonts' OFL requires the license alongside the font files (audit A2). A package without a
 * license file fails the build instead of shipping silently.
 */
function licenseNotices(): Plugin {
  /** Folder of `name` as Node resolves it from `from`: nested first, then the top level. */
  const pkgDir = (name: string, from: string): string => {
    const nested = join(from, 'node_modules', name);
    return existsSync(nested) ? nested : join('node_modules', name);
  };
  return {
    name: 'license-notices',
    apply: 'build',
    generateBundle(_options, bundle) {
      const seen = new Map<string, string>();
      const visit = (dir: string): void => {
        const meta = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8')) as {
          name: string;
          version: string;
          license?: string;
          dependencies?: Record<string, string>;
        };
        const key = `${meta.name}@${meta.version}`;
        if (seen.has(key)) return;
        const file = readdirSync(dir).find((f) => /^licen[cs]e(\.|$)/i.test(f));
        if (!file) throw new Error(`license-notices: ${key} has no license file`);
        seen.set(
          key,
          `${key} — ${meta.license ?? 'see text'}\n\n${readFileSync(join(dir, file), 'utf8').trim()}`,
        );
        for (const dep of Object.keys(meta.dependencies ?? {})) visit(pkgDir(dep, dir));
      };
      for (const output of Object.values(bundle)) {
        if (output.type !== 'chunk') continue;
        for (const id of Object.keys(output.modules)) {
          const root = packageRootOf(id);
          if (root) visit(root);
        }
      }
      const texts = [...seen.keys()].sort().map((k) => seen.get(k));
      this.emitFile({
        type: 'asset',
        fileName: 'third-party-licenses.txt',
        source: `Third-party licenses\n\n${texts.join(`\n\n${'-'.repeat(72)}\n\n`)}\n`,
      });
    },
  };
}

// https://vite.dev/config/
export default defineConfig(({ command }) => ({
  define: {
    // Injected at build time — allows the UI to show the exact build date.
    // In dev mode, shows 'dev' so it's clear this is not a deployed build.
    __BUILD_DATE__: JSON.stringify(
      command === 'build' ? new Date().toISOString().slice(0, 16).replace('T', ' ') : 'dev',
    ),
  },
  base: '/soundboard-of-storytelling/',
  plugins: [
    preact(),
    licenseNotices(),
    VitePWA({
      // A new version waits until the user taps RELOAD (src/components/UpdatePrompt.tsx,
      // ADR-0066) — never a reload in the middle of a game. Hence no skipWaiting / clientsClaim:
      // the prompt appears while the new service worker is waiting.
      registerType: 'prompt',
      workbox: {
        // woff2: the self-hosted fonts must be there offline (audit A2); every supported
        // browser reads woff2, so the woff fallbacks are not precached.
        globPatterns: ['**/*.{js,css,html,ico,png,svg,woff2}'],
      },
      manifest: {
        name: 'Soundboard of Storytelling',
        short_name: 'SoS',
        description: 'A soundboard for tabletop storytelling',
        start_url: '/soundboard-of-storytelling/',
        scope: '/soundboard-of-storytelling/',
        display: 'standalone',
        orientation: 'any',
        background_color: '#0a0a14',
        theme_color: '#0a0a14',
        icons: [
          {
            src: 'icon-192.png',
            sizes: '192x192',
            type: 'image/png',
            purpose: 'any',
          },
          {
            src: 'icon-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
    }),
  ],
}));
